import chalk from "chalk";
import * as fs from "fs/promises";
import * as path from "path";
import { ScreeningResult } from "./screener";
import { AIPoolRanking } from "./pool-inference";

/**
 * PoolReporter — Pretty-prints the 0G AI ranking result to stdout
 * and optionally exports a JSON report.
 */
export class PoolReporter {
  /**
   * Print the full AI-generated ranking table and top recommendation.
   */
  print(result: ScreeningResult, topN: number = 5): void {
    const { aiResult } = result;
    const rankings = aiResult.rankings.slice(0, topN);

    console.log("\n");
    console.log(chalk.bold.cyan(`📈 GROQ STRATEGIC PORTFOLIO ANALYSIS`));
    console.log(`   Analyzed: ${result.inputPools.length} pools  |  ${new Date().toISOString()}\n`);

    console.log(chalk.green("   ✅ Rankings generated by 0G Compute Sealed AI (TEE-verified, comparative)\n"));

    // ─── Market Summary from AI ──────────────────────────────────
    console.log(chalk.bold.white("📈 AI Market Summary:"));
    console.log(chalk.gray(`   ${aiResult.summary}\n`));

    // ─── Table header ────────────────────────────────────────────
    const header =
      chalk.bold.white(this.pad("Rank", 6)) +
      chalk.bold.white(this.pad("Pool", 14)) +
      chalk.bold.white(this.pad("Decision", 10)) +
      chalk.bold.white(this.pad("Risk", 7)) +
      chalk.bold.white(this.pad("Confidence", 12)) +
      chalk.bold.white(this.pad("Est. Return", 13)) +
      chalk.bold.white("AI Reasoning (brief)");

    console.log(header);
    console.log(chalk.gray("─".repeat(100)));

    for (const entry of rankings) {
      console.log(this.formatRow(entry));
    }

    console.log(chalk.gray("─".repeat(100)));

    // ─── Top Pick Deep-Dive ──────────────────────────────────────
    const top = aiResult.bestPool;
    const medal = "🏆";

    console.log(chalk.bold.yellow(`\n${medal}  BEST POOL TO INVEST: ${top.poolName}`));
    console.log(chalk.green(`    Decision       : ${top.action.toUpperCase()}`));
    console.log(chalk.green(`    Risk Score      : ${top.riskScore}/10`));
    console.log(chalk.green(`    AI Confidence   : ${top.confidenceScore}/100`));
    console.log(chalk.cyan( `    Expected Return : ${top.expectedReturn}`));
    console.log(chalk.white(`\n    🧠 Full AI Reasoning:`));
    console.log(chalk.gray( `    "${top.reasoning}"`));

    if (top.analysis_breakdown) {
      console.log(chalk.bold.cyan(`\n    🎯 STRATEGIC DEEP-DIVE (QUADRANT ANALYSIS):`));
      console.log(chalk.white(`     • 📊 On-Chain  : ${top.analysis_breakdown.onchain_analysis}`));
      console.log(chalk.white(`     • 📈 Market    : ${top.analysis_breakdown.market_analysis}`));
      console.log(chalk.white(`     • 🌐 Social    : ${top.analysis_breakdown.social_analysis}`));
      console.log(chalk.white(`     • 💰 Yield     : ${top.analysis_breakdown.yield_analysis}`));
      console.log(chalk.white(`     • 🛡️  Mitigation: ${top.analysis_breakdown.risk_mitigation}`));
    }


    // ─── Source label ────────────────────────────────────────────
    console.log(chalk.cyan("\n    🔐 Source: 0G Compute Sealed Inference — privacy-preserved, TEE-verified."));

    console.log("\n" + chalk.bold.cyan("═".repeat(100)) + "\n");
  }

  /**
   * Export the full AI result to a JSON report file.
   */
  async exportJSON(result: ScreeningResult, outputDir: string = "."): Promise<string> {
    const filename = `pool-report-${result.timestamp}.json`;
    const outPath  = path.resolve(outputDir, filename);

    const exportData = {
      generatedAt:    new Date(result.timestamp).toISOString(),
      aiEngine:       result.aiResult.usedFallback ? "LOCAL_FALLBACK" : "0G_COMPUTE_TEE",
      totalAnalyzed:  result.totalAnalyzed,
      topPick:        result.aiResult.bestPool.poolName,
      marketSummary:  result.aiResult.summary,
      rankings:       result.aiResult.rankings,
      inputPools:     result.inputPools,
    };

    await fs.writeFile(outPath, JSON.stringify(exportData, null, 2), "utf-8");
    console.log(chalk.green(`\n💾 [Report] Full AI analysis exported → ${outPath}`));
    return outPath;
  }

  // ── Helpers ───────────────────────────────────────────────────────

  private formatRow(r: AIPoolRanking): string {
    const rankLabel =
      r.rank === 1 ? "🥇 #1" :
      r.rank === 2 ? "🥈 #2" :
      r.rank === 3 ? "🥉 #3" :
      `    #${r.rank}`;

    const actionColor =
      r.action === "invest" ? chalk.bold.green :
      r.action === "watch"  ? chalk.bold.yellow :
      chalk.bold.red;

    const riskColor =
      r.riskScore <= 3 ? chalk.green :
      r.riskScore <= 6 ? chalk.yellow :
      chalk.red;

    const confColor =
      r.confidenceScore >= 75 ? chalk.green :
      r.confidenceScore >= 50 ? chalk.yellow :
      chalk.red;

    const shortReason = r.reasoning.length > 45
      ? r.reasoning.slice(0, 45) + "…"
      : r.reasoning;

    return (
      this.pad(rankLabel, 6) +
      this.pad(r.poolName, 14) +
      actionColor(this.pad(r.action.toUpperCase(), 10)) +
      riskColor(this.pad(`${r.riskScore}/10`, 7)) +
      confColor(this.pad(`${r.confidenceScore}/100`, 12)) +
      chalk.cyan(this.pad(r.expectedReturn, 13)) +
      chalk.gray(shortReason)
    );
  }

  private pad(str: string, len: number): string {
    const clean = str.replace(/\x1b\[[0-9;]*m/g, "");
    return str + " ".repeat(Math.max(0, len - clean.length));
  }
}
